IF OBJECT_ID("tempdb..#bs") IS NOT NULL
    DROP TABLE #bs

CREATE TABLE #bs (
    PLAYER VARCHAR(100) NOT NULL,
    MP VARCHAR(10) NULL,
    FG INT NULL,
    FGA INT NULL,
    FGP FLOAT NULL,
    3P INT NULL,
    3PP FLOAT NULL,
    FT INT NULL,
    FTA INT NULL,
    FTP FLOAT NULL,
    ORB INT NULL,
    DRB INT NULL,
    TRB INT NULL,
    AST INT NULL,
    STL INT NULL,
    BLK INT NULL,
    TOV INT NULL,
    TEAM VARCHAR(5) NULL,
    PF INT NULL,
    PTS INT NULL,
    PLUSMINUS INT NULL,
    GAMEDATE DATE NOT NULL
)

INSERT INTO #bs (PLAYER, MP, FG, FGA, FGP, 3P, 3PP, FT, FTA, FTP, ORB, DRB, TRB, AST, STL, BLK, TOV, TEAM, PF, PLUSMINUS, GAMEDATE) VALUES {};

-- SELECT * FROM #bs